name: Test composite workflow + SAST

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint bandit
    - name: Analysing the code with pylint and bandit
      run: |
        pylint $(git ls-files '*.py') |
        bandit -rlll $(git ls-files '*.py')
        
    - name: Build and up application
      id: first_test
      uses: ./security_env_action
      with:
        dockerfile-path: api/app/Dockerfile
        name_for_image: appv1
        port_forwarding: 8000:8000
        context_dir: api
